metricbeat.modules:
- module: docker
  metricsets: ["container", "cpu", "diskio", "event", "healthcheck", "image", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 600s

- module: postgresql
  metricsets: ["database", "bgwriter", "activity"]
  period: 600s
  hosts: ["postgres://postgresBd:5432"]
  username: postgres
  password: postgres

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

setup.dashboards.enabled: true